### ISSUE TITLE
Hit Points

### ISSUE THREAD

**Issue by docphil30** [JDR-Ninja/foundryvtt-mgt2#1]
Je suis surpris de la notion de points de Vie, les dégâts se prenant normalement sur les caractéristiques physiques.

I'm surprised by the notion of hit points, as damage is normally taken from physical characteristics.

**Comment by JDR-Ninja** [comment]
En fait ils sont calculé en fonction de la STRENGTH, DEXTERITY et ENDURANCE. Ça permet d'avoir une barre sur le token. Il y a une option pour la cacher de la feuille de personnage.

**Comment by docphil30** [comment]
Oui, j’ai bien compris le calcul mais les dégâts sont appliqués directement sur la caractéristique, normalement, ce qui influe directement dur son modificateur et donc sur les jets de compétences s’y référant.

Envoyé à partir de Courrier pour Windows

De : JDR-Ninja
Envoyé le :vendredi 10 mai 2024 18:13
À : JDR-Ninja/foundryvtt-mgt2
Cc : docphil30; Author
Objet :Re: [JDR-Ninja/foundryvtt-mgt2] Hit Points (Issue #1)

En fait ils sont calculé en fonction de la STRENGTH, DEXTERITY et ENDURANCE. Ça permet d'avoir une barre sur le token. Il y a une option pour la cacher de la feuille de personnage.

**Comment by JDR-Ninja** [comment]
Et c'est exactement de cette manière que le système calcul les dégâts. La section "Vie" est optionnel (option dans la configuration) et peut être caché. Et c'est une section auto calculé, impossible de l'éditer.

Lors de l'application de dégâts, les dégâts sont appliqué sur les 3 caractéristiques de l'acteur selon sa configuration. Ensuite les modificateurs sont recalculé et la Vie aussi.

**Comment by docphil30** [comment]
Ok, tant mieux, j’avoue ne pas comprendre l’utilité de ce cumul que je n’ai vu apparaitre nulle part dans les règles (du moins, il me semble). Je comprends l’idée d’avoir une barre de vie mais il vaudrait mieux pouvoir en afficher 3 (For,dex, Endu). Je ne sais si on peut en afficher autant sur le HUD ☹. En tout cas merci de se lancer dans cette entreprise !

Envoyé à partir de Courrier pour Windows

De : JDR-Ninja
Envoyé le :samedi 11 mai 2024 14:49
À : JDR-Ninja/foundryvtt-mgt2
Cc : docphil30; Author
Objet :Re: [JDR-Ninja/foundryvtt-mgt2] Hit Points (Issue #1)

Et c'est exactement de cette manière que le système calcul les dégâts. La section "Vie" est optionnel (option dans la configuration) et peut être caché. Et c'est une section auto calculé, impossible de l'éditer.
Lors de l'application de dégâts, les dégâts sont appliqué sur les 3 caractéristiques de l'acteur selon sa configuration. Ensuite les modificateurs sont recalculé et la Vie aussi.
